name: 'JIRA lint action'
description: 'Consistency check between pull requests and JIRA issues'
author: 'Lars Bekkema'
inputs:
  github-token:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
  skip-branches:
    description: "List of branch names to skip JIRA ticket check (eg. 'no-jira,dependabot,release')"
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
