name: 'JIRA lint action'
description: 'Consistency check between pull requests and JIRA issues'
author: 'Lars Bekkema'
inputs:
  github-token:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
  branch-term-whitelist:
    description: 'List of terms to look for to whitelist the branch (ignore JIRA ticket check)'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
