name: 'build-test'
on:
  pull_request:
    types:
      - synchronize
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn install

      - name: build, format, lint, package and test
        run: yarn all

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run JIRA lint action
        uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-term-whitelist: 'dependabot'
